/* tslint:disable */
import './班课详情'
import './导航'
import './teach'
import './dashboard'
import './example'
import './eye-off'
import './eye-on'
import './form'
import './hamburger'
import './link'
import './nested'
import './password'
import './table'
import './tool'
import './tree'
import './user'
